name: Build and Release APK

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out repository under $GITHUB_WORKSPACE
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Java (Temurin JDK 17)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      # Clean the project before building (optional, but recommended)
      - name: Clean project
        run: ./gradlew clean

      # Build APK
      - name: Build APK
        run: ./gradlew assembleRelease --no-daemon

      # Install Android tools (zipalign, apksigner)
      - name: Install Android tools
        run: |
          sudo apt-get update
          sudo apt-get install zipalign apksigner

      # Sign APK
      - name: Sign APK
        run: |
          cd app/build/outputs/apk/full/release/
          echo "$APK_RELEASE_KEY_BASE64" | base64 -d > release-key.jks
          zipalign -v -p 4 app-full-release-unsigned.apk app-full-release-unsigned-aligned.apk
          apksigner sign --ks release-key.jks --ks-pass pass:"$APK_RELEASE_KEY_PASSWORD" --out "aaps-${{ github.ref_name }}.apk" app-full-release-unsigned-aligned.apk
        env:
          APK_RELEASE_KEY_BASE64: ${{ secrets.APK_RELEASE_KEY_BASE64 }}
          APK_RELEASE_KEY_PASSWORD: ${{ secrets.APK_RELEASE_KEY_PASSWORD }}
          REF_NAME: ${{ github.ref_name }}

      # Release APK to GitHub Releases
      - name: Release APK
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/full/release/aaps-${{ github.ref_name }}.apk
